---
- name: Distribute CLD1, CLD2, and CLD3 Folders to CTngexp on All Relevant Hosts
  hosts: Monitor # Targeting CA, Logger, Monitor, and Control hosts
  tasks:
    - name: Distribute CLD1 folder to /tmp/CTngexp/CLD1
      copy:
        src: ../CTngexp/CLD1
        dest: /tmp/CTngexp

    - name: Distribute CLD2 folder to /tmp/CTngexp/CLD2
      copy:
        src: ../CTngexp/CLD2
        dest: /tmp/CTngexp

    - name: Distribute CLD3 folder to /tmp/CTngexp/CLD3
      copy:
        src: ../CTngexp/CLD3
        dest: /tmp/CTngexp
