---
- name: Distribute Entire CTngexp Folder to All Relevant Hosts
  hosts: CA, Logger, Monitor,Control  # This will target all the CA, Logger, and Monitor hosts
  tasks:
    - name: Create CTngexp folder in /tmp/CTngexp
      ansible.builtin.file:
        path: /tmp/CTngexp/DMLCG
        state: directory  # Ensure the directory exists

    - name: Distribute files to DMLCG folder in /tmp/CTngexp
      copy:
        src: ../CTngexp/DMLCG  # Relative path pointing to CTngexp folder from one level up
        dest: /tmp/CTngexp/  # Absolute path on the remote hosts
