---
- name: Distribute Entire CTngexp Folder to All Relevant Hosts
  hosts: CA, Logger, Monitor,Control  # This will target all the CA, Logger, and Monitor hosts
  tasks:
    - name: Create CTngexp folder in /tmp
      ansible.builtin.file:
        path: /tmp/CTngexp
        state: directory  # Ensure the directory exists

    - name: Distribute files to CTngexp folder in /tmp
      copy:
        src: ../CTngexp/  # Relative path pointing to CTngexp folder from one level up
        dest: /tmp/CTngexp/  # Absolute path on the remote hosts

    - name: Run go build using full path to go binary
      ansible.builtin.command:
        cmd: /tmp/go/bin/go build .
      args:
        chdir: /tmp/CTngexp
